### ISSUE TITLE
Canot use for InDesign, because of the gripper. 

### ISSUE THREAD

**Issue by vamitul** [cAttte/ruxp#1]
```
ERROR in ./node_modules/ruxp/dist/components/Panel.js 12:29-49
Module not found: Error: Can't resolve 'photoshop'
```

**Comment by cAttte** [comment]
hey! thanks for reporting this. it's weird that you're getting this error regardless of the `catch()`. i'll install InDesign and test this out ~~when i get home~~ as soon as i can. is everything else working fine?

**Comment by cAttte** [comment]
so, for some reason a random error was being thrown instead of the promise being rejected, so the `catch()` didn't catch it. whatever, it's wrapped in a try..catch now. i'll work on getting a release ready
